repos:
  - repo: https://github.com/ambv/black
    rev: 24.1.1
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args:
        - "--profile=black"
        - "--filter-files"
        - "--project=autora"
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args:
        - "--max-line-length=100"
        - "--extend-ignore=E203"
        - "--per-file-ignores=__init__.py:F401"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.991"
    hooks:
      - id: mypy
        additional_dependencies: [types-requests]
        language_version: python3.10
default_language_version:
  python: python3
